In [2]:
import numpy as np
from numpy.random import randn

In [6]:
np.set_printoptions(precision=2)

In [7]:
a = np.arange(3)
a

array([0, 1, 2])

In [8]:
aa = np.array([[2.,4.,5.],[1.,3.,5.],[10.,20.,30.] ])
aa

array([[ 2.,  4.,  5.],
       [ 1.,  3.,  5.],
       [10., 20., 30.]])

In [9]:
a*aa

array([[ 0.,  4., 10.],
       [ 0.,  3., 10.],
       [ 0., 20., 60.]])

In [13]:


bb = np.arange(9).reshape((3,3))
bb

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [14]:
np.dot(aa,bb)

array([[ 42.,  53.,  64.],
       [ 39.,  48.,  57.],
       [240., 300., 360.]])